### ISSUE TITLE
Api key is exposed

### ISSUE THREAD

**Issue by Murat-Karakaya** [TJRelly/smart-brain#9]
I won't openly discuss this issue. Beacuse  if I do, other github users will also have full acces to your clarifai api key.
If you want to make your code more secure, watch [this](https://www.udemy.com/course/the-complete-web-developer-zero-to-mastery/learn/lecture/8915974#overview).

Also, you should probably make your smart-brain-api repository private once you made those changes in the video.

If you can't watch the video, please let me know :)

**Comment by TJRelly** [comment]
Thank you for the reminder. I appreciate your discretion.

**Comment by Murat-Karakaya** [comment]
Your welcome.

**Comment by TJRelly** [comment]
The video wasn't helpful, but I solved the issue when I looked at the code base. It was challenging, but fun.
